# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    #-   id: trailing-whitespace
    #-   id: end-of-file-fixer
    -   id: check-yaml
        args: [--unsafe]
    -   id: check-added-large-files
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable
    - id: pretty-format-json
      args:
        - "--autofix"
        - "--indent=4"
        - "--no-sort-keys"
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.4
    hooks:
    -   id: clang-format
        types_or: [c++, c]
-   repo: https://github.com/jorisroovers/gitlint
    rev: 'v0.19.1'
    hooks:
    -   id: gitlint
-   repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
    - id: cmake-format
    - id: cmake-lint
      args: [--config=.cmakelint.py]

